# Generated by Django 4.1.7 on 2023-03-31 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_foodcategory_remove_cuisine_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcategory',
            old_name='name',
            new_name='national_origin',
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25000)]),
        ),
    ]
